/**
 * @description
 * This server component hosts the main user flow for "WhatWillItMeantome".
 * It includes a form where the user enters career data, calls Mistral AI,
 * and displays the resulting analysis plus a shareable placard image generator.
 *
 * It is responsible for:
 * - Returning a simple server layout that loads the client boundary
 * - Rendering disclaimers to emphasize the speculative nature of AI predictions
 *
 * Key features:
 * - Minimal usage: we define a state for MistralResponse in a client boundary
 * - The client boundary handles the AI calls and final display
 * - A disclaimer about the unpredictability of the future
 *
 * @dependencies
 * - handleMistralAction from "@/actions/ai/handle-mistral-actions" (called in the child)
 * - PageClientBoundary from "./page-client-boundary"
 *
 * @notes
 * - The disclaimers are also repeated in the final report. This extra note ensures
 *   the user sees them at multiple points in the flow.
 */

"use server"

import React from "react"
import PageClientBoundary from "./page-client-boundary"

export default async function WhatWillItMeantomePage() {
  return (
    <div className="space-y-6 p-6">
      {/* Main Content */}
      <PageClientBoundary />

      {/* Additional Disclaimer */}
      <div className="text-muted-foreground pt-8 text-sm">
        <p className="mb-2 font-semibold">Important Disclaimer</p>
        <p>
          The analysis and predictions on this site are generated by an AI
          system and are intended for discussion and awareness purposes only.
          Nobody knows the future for certain. You should always do your own
          research and consult professionals before making major career
          decisions.
        </p>
      </div>
    </div>
  )
}
