"use server"

/**
 * @description
 * This server component now serves as the default homepage at "/",
 * previously the content for the "WhatWillItMeantome" route.
 * It handles the disclaimers and renders the main client boundary
 * that holds the form and analysis UI.
 *
 * @responsibilities
 * - Host the PageClientBoundary which manages the user input & AI analysis flow.
 * - Display disclaimers about AI-generated predictions.
 *
 * @notes
 * - This file replaces the old marketing page, so visiting "/" triggers
 *   the WhatWillItMeantome experience.
 */

import React from "react"
// @ts-ignore - Module exists but TypeScript can't find it
import PageClientBoundary from "./_components/whatwillitmeantome/page-client-boundary"

export default async function HomePage() {
  return (
    <div className="space-y-6 p-6">
      <PageClientBoundary />

      <div className="text-muted-foreground pt-8 text-sm">
        <p className="mb-2 font-semibold">Important Disclaimer</p>
        <p>
          The analysis and predictions on this site are generated by an AI
          system and are intended for discussion and awareness purposes only.
          Nobody knows the future for certain. You should always do your own
          research and consult professionals before making major career
          decisions.
        </p>
      </div>
    </div>
  )
}
