/**
 * @description
 * This server component is now the main homepage at "/".
 * It centralizes the AI form for analyzing the impact of AGI on a profession,
 * merges disclaimers, and displays results in a single place.
 *
 * Responsibilities:
 * - Render a client subcomponent (<HomeClient>) that handles the form input and results display
 * - Provide a single disclaimers block at the bottom
 * - Serve as the main landing page for the "WhatWillItMeanToMe" experience
 *
 * Key Features:
 * - Single-page approach to user input -> AI analysis -> result output
 * - Minimal duplication of disclaimers, removing old references
 *
 * @notes
 * - All logic from the old "whatwillitmeantome" route is now consolidated here
 * - The disclaimers are shown only once, at the bottom of the page
 */

import React, { Suspense } from "react"
import HomeClient from "@/app/_home-client"
import Header from "@/components/landing/header"
import Footer from "@/components/landing/footer"

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />

      <div className="flex-1 px-4 py-8 md:px-8 md:py-12">
        <div className="flex w-full flex-col items-center justify-center">
          {/**
           * We use a Suspense boundary in case the client fetch has a small delay,
           * though not strictly necessary if there's no SSR data needed.
           */}
          <Suspense
            fallback={
              <div className="text-muted-foreground mt-8 text-sm">
                Loading...
              </div>
            }
          >
            <HomeClient />
          </Suspense>

          {/**
           * Single unified disclaimer to avoid duplicates.
           */}
          <div className="text-muted-foreground max-w-3xl pt-8 text-center text-sm">
            <p className="mb-2 font-semibold">Important Disclaimer</p>
            <p>
              The analysis and predictions on this site are generated by an AI
              system and are intended for discussion and awareness purposes
              only. Nobody knows the future for certain. You should not make
              career or financial decisions based solely on this information.
            </p>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  )
}
